server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            redirect-uri: "https://alumverse.netlify.app/oauth2/callback"
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
            redirect-uri: "https://alumverse.netlify.app/oauth2/callback"